export const foundations = {
  "--ae-workbench-accent": "var(--ae-theme-accent)",
  "--ae-workbench-accent-soft": "var(--ae-theme-accent-soft)",
  "--ae-workbench-accent-contrast": "var(--ae-theme-accent-contrast)",
  "--ae-workbench-ambient": "var(--ae-theme-ambient)",

  "--ae-max": "1280px",
  "--ae-palette-dark-amber": "#ffce6d",
  "--ae-palette-dark-orange": "#f47a4f",
  "--ae-palette-dark-red": "#d73d3d",
  "--ae-palette-dark-plum": "#6e2743",
  "--ae-palette-dark-accent": "#ff7650",
  "--ae-palette-dark-accent-soft": "#ffbd69",
  "--ae-font-sans": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  "--ae-font-serif": "Georgia, \"Times New Roman\", serif",
  "--ae-font-mono": "ui-monospace, SFMono-Regular, Consolas, monospace",
  "--ae-radius-panel": "8px",
  "--ae-workbench-radius-panel": "14px",
  "--ae-workbench-radius-control": "8px",
  "--ae-workbench-radius-dialog": "18px",
  "--ae-radius-control": "0px",
  "--ae-radius-pill": "999px",
  "--ae-focus-width": "2px",
  "--ae-focus-offset": "5px",
  "--ae-motion-reduced": ".01ms",
  "--ae-logo-size": "36px",
  "--ae-skip-ink": "#17100c",
  "--ae-control-ink": "#21130d",
  "--ae-space-2": "2px",
  "--ae-space-4": "4px",
  "--ae-space-8": "8px",
  "--ae-space-12": "12px",
  "--ae-space-16": "16px",
  "--ae-space-20": "20px",
  "--ae-space-24": "24px",
  "--ae-space-32": "32px",
  "--ae-space-48": "48px",
  "--ae-space-64": "64px",
  "--ae-text-8": "8px",
  "--ae-text-9": "9px",
  "--ae-text-10": "10px",
  "--ae-text-11": "11px",
  "--ae-text-12": "12px",
  "--ae-text-13": "13px",
  "--ae-text-14": "14px",
  "--ae-text-15": "15px",
  "--ae-text-16": "16px",
  "--ae-text-17": "17px",
  "--ae-text-18": "18px",
  "--ae-text-19": "19px",
  "--ae-text-20": "20px",
  "--ae-text-22": "22px",
  "--ae-text-23": "23px",
  "--ae-text-24": "24px",
  "--ae-text-26": "26px",
  "--ae-text-30": "30px",
  "--ae-text-31": "31px",
  "--ae-text-32": "32px",
  "--ae-text-36": "36px",
  "--ae-text-38": "38px",
  "--ae-text-39": "39px",
  "--ae-text-49": "49px",
  "--ae-text-51": "51px",
  "--ae-text-52": "52px",
  "--ae-text-57": "57px",
  "--ae-text-65": "65px",
  "--ae-text-66": "66px",
  "--ae-text-70": "70px",
  "--ae-text-76": "76px",
  "--ae-text-77": "77px",
  "--ae-text-78": "78px",
  "--ae-text-90": "90px",
  "--ae-text-94": "94px",
  "--ae-text-96": "96px",
  "--ae-text-105": "105px",
  "--ae-text-107": "107px",
  "--ae-text-120": "120px",
  "--ae-text-130": "130px",
  "--ae-text-138": "138px",
  "--ae-text-260": "260px",
  "--ae-dashboard-ink": "#f4f0e8",
  "--ae-dashboard-muted": "#92989a",
  "--ae-dashboard-line": "rgba(244, 240, 232, .16)",
  "--ae-dashboard-panel": "#121b27",
  "--ae-dashboard-background": "#080d15",
  "--ae-dashboard-orange": "#fa7651",
  "--ae-dashboard-gold": "#f6bb6e",
  "--ae-dashboard-copy": "#bdc0bd",
  "--ae-dashboard-evidence": "#bfc0ba",
  "--ae-dashboard-input": "rgba(255,255,255,.025)",
  "--ae-dashboard-track": "rgba(255,255,255,.08)"
} as const;

export const lightTheme = {
  "--ae-theme-accent": "var(--ae-accent)",
  "--ae-theme-accent-soft": "var(--ae-accent-soft)",
  "--ae-theme-accent-contrast": "var(--ae-accent-contrast)",
  "--ae-theme-ambient": "var(--ae-ambient)",

  "--ae-status-progress": "#a54127",
  "--ae-status-progress-surface": "#f9e7df",
  "--ae-status-progress-line": "#e5baa8",
  "--ae-status-progress-fill": "#c65031",
  "--ae-status-ready": "#28704f",
  "--ae-status-ready-surface": "#e2f1e8",
  "--ae-status-ready-line": "#b2d8c1",
  "--ae-status-attention": "#86591f",
  "--ae-status-attention-surface": "#fbefd9",
  "--ae-status-attention-line": "#dfc69b",
  "--ae-workbench-active-surface": "linear-gradient(115deg, #ffd3af, #ffe5cc 65%, #fff0df)",
  "--ae-workbench-shadow": "0 3px 12px rgba(24,37,54,.045)",

  "--ae-ink": "#182536",
  "--ae-ink-strong": "#0f1a29",
  "--ae-muted": "#66717b",
  "--ae-body-copy": "#334353",
  "--ae-prose": "#29394a",
  "--ae-line": "rgba(24, 37, 54, .17)",
  "--ae-panel": "#fffaf3",
  "--ae-background": "#f5f0e8",
  "--ae-page-background": "var(--ae-background)",
  "--ae-accent": "#c65031",
  "--ae-accent-soft": "#b8682c",
  "--ae-accent-contrast": "#fff9ef",
  "--ae-ambient": "rgba(214, 91, 61, .08)",
  "--ae-ambient-warm": "rgba(255, 188, 103, .2)",
  "--ae-sky-center": "var(--ae-background)",
  "--ae-sky-mid": "var(--ae-background)",
  "--ae-field-recess": "#081422",
  "--ae-field-cut": "#142332",
  "--ae-field-edge-top": "#9ba9b2",
  "--ae-field-edge-side": "#cad3d7",
  "--ae-field-edge-bottom": "#fffdf7",
  "--ae-field-lip-width": "6"
} as const;

export const darkTheme = {
  "--ae-theme-accent": "#9ebdff",
  "--ae-theme-accent-soft": "#bfd2ff",
  "--ae-theme-accent-contrast": "#101a2d",
  "--ae-theme-ambient": "#23385e",

  "--ae-status-progress": "#b5ccff",
  "--ae-status-progress-surface": "#23385e",
  "--ae-status-progress-line": "#45649a",
  "--ae-status-progress-fill": "#8aaaff",
  "--ae-status-ready": "#a1d5b9",
  "--ae-status-ready-surface": "#203b30",
  "--ae-status-ready-line": "#3c6652",
  "--ae-status-attention": "#e3c28d",
  "--ae-status-attention-surface": "#352c21",
  "--ae-status-attention-line": "#695338",
  "--ae-workbench-active-surface": "linear-gradient(115deg, #223875, #1d2b55 65%, #1b2748)",
  "--ae-workbench-shadow": "0 3px 12px rgba(0,0,0,.12)",

  "--ae-ink": "#f3f1ec",
  "--ae-ink-strong": "#fffaf2",
  "--ae-muted": "#a8a9a7",
  "--ae-body-copy": "#c7c8c4",
  "--ae-prose": "#dbd9d3",
  "--ae-line": "rgba(243, 241, 236, .17)",
  "--ae-panel": "#121822",
  "--ae-background": "#080d18",
  "--ae-sky-center": "#213a50",
  "--ae-sky-mid": "#121c2c",
  "--ae-page-background": "radial-gradient(ellipse at 78% 30%, var(--ae-sky-center), var(--ae-sky-mid) 48%, var(--ae-background) 100%)",
  "--ae-accent": "var(--ae-palette-dark-accent)",
  "--ae-accent-soft": "var(--ae-palette-dark-accent-soft)",
  "--ae-accent-contrast": "#21130d",
  "--ae-ambient": "rgba(214, 61, 61, .12)",
  "--ae-ambient-warm": "rgba(255, 188, 103, .12)",
  "--ae-field-lip-width": "0",
  "--ae-field-recess": "#101d2bea",
  "--ae-field-cut": "#0c1523",
  "--ae-field-edge-top": "#050b13",
  "--ae-field-edge-side": "#34465a",
  "--ae-field-edge-bottom": "#64768a"
} as const satisfies Record<keyof typeof lightTheme, string>;

export type DesignToken = keyof typeof foundations | keyof typeof lightTheme;
