import type { SystemManifest } from '../manifests/schema/system.schema.ts';

export default {
  kind: 'system',
  id: 'system-explorer',
  name: 'AE System Explorer',
  purpose: 'Explore approved systems, contracts, connections, and governance.',
  owner: 'amazingefren',
  status: 'declared',
  visibility: 'public',
  decisions: [
    'Offer approved system descriptions, contracts, and verification metadata as JSON and readable text.',
    'Expose approved catalog fields only, including private engine projections. Never project workbench.',
    'Include source revisions; distinguish declared governance from verified behavior.',
    'Ship bindings with their operation; implement and independently verify each adapter.',
  ],
  capabilities: [
    'system-discovery',
    'architecture-exploration',
    'portable-system-catalog',
  ],
  governance: {
    permissionsDefined: [],
    dataClassification: 'public',
  },
  risks: [],
  dependencies: ['design', 'manifests'],
  schemaVersion: 6,
  contracts: [
    'contracts/api/catalog-list.schema.json',
    'contracts/api/catalog.schema.json',
    'contracts/api/errors.schema.json',
    'contracts/api/list-input.schema.json',
    'contracts/api/read-input.schema.json',
  ],
  operations: [
    {
      id: 'system-explorer.list',
      access: {
        kind: 'public',
      },
      bindings: [
        {
          id: 'system-explorer.list.http',
          surface: {
            kind: 'http',
            method: 'GET',
            path: '/api/systems',
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/http/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/http',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.list.mcp-tool',
          surface: {
            kind: 'mcp-tool',
            name: 'list_systems',
            description: 'List approved public systems.',
            readOnly: true,
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/mcp/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/mcp',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.list.cli',
          surface: {
            kind: 'cli',
            command: 'ae systems list',
            output: 'json',
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/cli/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/cli',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.list.export',
          surface: {
            kind: 'export',
            format: 'json',
            path: '/exports/systems/index.json',
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/exports/json/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/exports/json',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.list.offline',
          surface: {
            kind: 'export',
            format: 'offline-bundle',
            path: '/exports/systems.zip',
          },
          status: 'implemented',
          implementation:
            'system-explorer/adapters/exports/offline-bundle/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/exports/offline-bundle',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.list.onion',
          surface: {
            kind: 'mirror',
            network: 'onion',
            publicOnly: true,
            localAssets: true,
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/onion/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/onion',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.list.ipfs',
          surface: {
            kind: 'mirror',
            network: 'ipfs',
            publicOnly: true,
            localAssets: true,
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/ipfs/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/ipfs',
          testsDirectory: 'system-explorer/tests',
        },
      ],
      status: 'implemented',
      input: 'contracts/api/list-input.schema.json',
      output: 'contracts/api/catalog-list.schema.json',
      errors: 'contracts/api/errors.schema.json',
      implementation: 'system-explorer/operations/list/index.ts',
      verification: [
        {
          id: 'system-explorer.list.contract',
          category: 'contract',
          expectation: 'Input and output conform to the referenced schemas.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
        {
          id: 'system-explorer.list.access',
          category: 'access',
          expectation:
            'Only approved public data is returned; private fields never appear.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
        {
          id: 'system-explorer.list.behavior',
          category: 'behavior',
          expectation:
            'All delivery bindings return the same approved revision.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
        {
          id: 'system-explorer.list.failure',
          category: 'failure',
          expectation:
            'Invalid input and missing data produce defined failures.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
      ],
      directory: 'system-explorer/operations/list',
      testsDirectory: 'system-explorer/tests',
    },
    {
      id: 'system-explorer.read',
      access: {
        kind: 'public',
      },
      bindings: [
        {
          id: 'system-explorer.read.http',
          surface: {
            kind: 'http',
            method: 'GET',
            path: '/api/systems/{id}',
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/http/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/http',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.read.mcp-tool',
          surface: {
            kind: 'mcp-tool',
            name: 'read_systems',
            description: 'Read approved public systems.',
            readOnly: true,
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/mcp/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/mcp',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.read.cli',
          surface: {
            kind: 'cli',
            command: 'ae systems read <id>',
            output: 'json',
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/cli/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/cli',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.read.export',
          surface: {
            kind: 'export',
            format: 'json',
            path: '/exports/systems/{id}.json',
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/exports/json/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/exports/json',
          testsDirectory: 'system-explorer/tests',
        },
        {
          id: 'system-explorer.read.mcp-resource',
          surface: {
            kind: 'mcp-resource',
            uriTemplate: 'ae://systems/{id}',
            mimeType: 'application/json',
          },
          status: 'implemented',
          implementation: 'system-explorer/adapters/mcp/index.ts',
          tests: ['system-explorer/tests/adapters.test.ts'],
          directory: 'system-explorer/adapters/mcp',
          testsDirectory: 'system-explorer/tests',
        },
      ],
      status: 'implemented',
      input: 'contracts/api/read-input.schema.json',
      output: 'contracts/api/catalog.schema.json',
      errors: 'contracts/api/errors.schema.json',
      implementation: 'system-explorer/operations/read/index.ts',
      verification: [
        {
          id: 'system-explorer.read.contract',
          category: 'contract',
          expectation: 'Input and output conform to the referenced schemas.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
        {
          id: 'system-explorer.read.access',
          category: 'access',
          expectation:
            'Only approved public data is returned; private fields never appear.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
        {
          id: 'system-explorer.read.behavior',
          category: 'behavior',
          expectation:
            'All delivery bindings return the same approved revision.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
        {
          id: 'system-explorer.read.failure',
          category: 'failure',
          expectation:
            'Invalid input and missing data produce defined failures.',
          tests: ['system-explorer/tests/catalog.test.ts'],
        },
      ],
      directory: 'system-explorer/operations/read',
      testsDirectory: 'system-explorer/tests',
    },
  ],
  capabilityPaths: {
    'system-discovery': 'system-explorer/domain/catalog',
    'architecture-exploration': 'system-explorer/ui/graph',
    'portable-system-catalog': 'system-explorer/adapters/exports/json',
  },
  structure: {
    domain: 'system-explorer/domain',
    operations: 'system-explorer/operations',
    ports: 'system-explorer/ports',
    adapters: 'system-explorer/adapters',
    tests: 'system-explorer/tests',
    composition: 'system-explorer/composition',
  },
} as const satisfies SystemManifest;
