import type { DesignManifest } from './contracts/design.schema.ts';

export default {
  kind: 'system',
  id: 'design',
  name: 'AE Design',
  purpose:
    'Own the shared visual language and interaction rules for AE interfaces.',
  owner: 'amazingefren',
  status: 'declared',
  scope: 'required',
  visibility: 'public',
  context: {
    decisions: [
      'This manifest and its referenced contracts are the design source of truth. Feature manifests own content, routes, operations, access, and page-specific composition.',
      'Approved visual direction: sun/light uses orange accents and the warm Shared circles mark; moon/dark uses blue accents and the blue mark. Keep warm paper, dark navy, restrained rules, and rounded workspace controls.',
      'Use sans serif for interfaces and body copy, serif for editorial emphasis and reading, and monospace for short metadata. Do not add font downloads.',
      'Keep content direct. Reuse approved personal text. Synthetic data and unavailable states must be explicit.',
      'Tokens compile into checked-in CSS so pages remain usable without JavaScript or private engines. Compiled CSS and served logo copies are not editing entrypoints.',
    ],
    openQuestions: [
      'Application implementation was authorized on 2026-09-09. User accepted the revised workspace as a starting point on 2026-09-09; owner identity and storage need live configuration.',
    ],
  },
  capabilities: [
    'foundations',
    'brand',
    'behaviors',
    'components',
    'design-validation',
  ],
  governance: { permissionsDefined: [], dataClassification: 'public' },
  risks: [],
  dependencies: [],
  schemaVersion: 5,
  languageVersion: 3,
  copy: {
    rules: [
      '2026-09-09: Prefer an interface change over text that explains the system. Keep text for names, actions, meaningful state, and essential knowledge the interface cannot convey.',
      'Keep text only when it names content, identifies a necessary state, explains a consequence, or helps recover from a failure.',
      'Do not add taglines, introductory filler, repeated headings, obvious instructions, or implementation explanations to application pages.',
      'Show sample-data scope once in the shared shell. Repeat it only where a distinct export or measurement could otherwise be mistaken for real data.',
      'Use one state label per record. Do not repeat the same state in a sentence, badge, and subtitle.',
      'Feature manifests own page content and composition; AE Design owns these copy rules. Preserve approved personal writing.',
      'Review all rendered page text before handoff. Static checks detect known filler, not editorial quality.',
    ],
    forbiddenUiPhrases: [
      'Tracked System Scope',
      'Accepted items show verified tracked work. They do not certify a whole system.',
      'A place for longer thoughts on software, applied AI, and the work around them.',
      'Original essays and stable copies will appear here as they are ready.',
      'A little bit of everything.',
      'All in one place.',
      'A look inside the tools, projects, and processes',
      'Each agent has a task, an owned area, and a handoff.',
      'Select a system to look inside',
      'frozen workspace contract',
      'What active would mean',
      'Role control',
      'Server supplied only',
      'Approved catalog',
      'Allowlisted data',
      'External boundaries',
      'Session boundary',
      'Saving never publishes.',
      'These are manifest metadata.',
    ],
  },
  interaction: {
    rules: [
      'Use action-primary, action-primary-hover, and action-primary-ink together for filled actions. Keep icons the same color as their label.',
      'Hover stays within the current palette: deeper orange in light mode, lighter blue in dark mode. Accent-soft is for emphasis, never a primary hover background.',
      'Neutral controls use hover-surface and hover-line. Preserve their text color. Selected navigation keeps its theme fill.',
      'Text links use an underline on hover. Do not fill a text link or a tab like a button.',
      'Disabled controls do not react to hover. Use low-specificity defaults so generic selectors cannot override selected, primary, or status controls.',
      'Review base, hover, focus, selected, and disabled states in both themes. Token membership alone does not verify their use.',
    ],
    forbiddenHoverTokens: [
      '--ae-accent',
      '--ae-accent-soft',
      '--ae-ambient',
      '--ae-theme-accent-soft',
      '--ae-theme-ambient',
    ],
    contrastPairs: [
      {
        foreground: '--ae-action-primary-ink',
        background: '--ae-action-primary',
        minimum: 4.5,
      },
      {
        foreground: '--ae-action-primary-ink',
        background: '--ae-action-primary-hover',
        minimum: 4.5,
      },
      {
        foreground: '--ae-ink',
        background: '--ae-hover-surface',
        minimum: 4.5,
      },
    ],
  },
  foundations: {
    source: 'design/foundations/tokens.ts',
    stylesheet: 'design/foundations/tokens.css',
    rules: [
      'Use --ae-* semantic colors; never introduce local hex, RGB, HSL, or named palette values. The artwork exception is limited to the declared illustration file.',
      'Use the shared font families, text sizes, space scale, focus tokens, and control radii. Local grid geometry and responsive composition belong to the owning page.',
      'Do not override a canonical token in feature CSS. Add a justified token or an approved pattern in AE Design.',
      'Use flat panels and fine borders. The public and workspace shells share --ae-page-background: warm paper in light mode and the approved radial navy gradient in dark mode. The featured progress card uses its separate status gradient. No new decorative gradients or badges.',
      'The existing text scale includes editorial sizes. Small metadata sizes are not a license to shrink body copy or controls.',
    ],
  },
  brand: {
    contract: 'design/brand/brand.ts',
    component: 'design/ui/BrandMark.tsx',
    rules: [
      'Use the Shared circles asset through BrandMark. Keep its viewBox, proportions, path geometry, and gradient stop positions. Theme colors use the declared asset variants.',
      'Use BrandMark variant theme for interfaces adopting the sun/moon design. It uses the warm color mark in light mode and blue in dark mode. Existing public consumers stay unchanged until their migration. The light monochrome variant is for dark backgrounds only.',
      'Keep surrounding text and icons clear of the mark. Use the standard navigation size unless a reviewed composition declares another size.',
      'Never redraw the mark, invent initials badges or module logos, stretch it, recolor it with filters, or add shadows.',
      'A decorative mark beside the site name has empty alternative text. A standalone meaningful mark requires an accessible name.',
    ],
  },
  behaviors: [
    {
      id: 'design.theme',
      status: 'approved',
      purpose: 'Select a local display preference.',
      implementation: 'design/behaviors/theme.ts',
      rules: [
        'System, light, and dark are the only choices.',
        'Use ae-theme storage and data-theme on the document root. System removes the explicit override.',
        'Apply before paint; storage failure must not block the page.',
        'Use the shared bootstrap and ThemeControl. Theme changes grant no permissions and send no analytics.',
      ],
    },
    {
      id: 'design.navigation',
      status: 'approved',
      purpose: 'Keep navigation and commands distinct.',
      implementation: null,
      rules: [
        'Links navigate or download; buttons perform actions.',
        'Set aria-current on the current destination. Never mark a disabled destination as a working link.',
        'Keep public navigation separate from the workbench sidebar.',
        'Icon-only controls need accessible names. Decorative arrows are hidden from assistive technology.',
      ],
    },
    {
      id: 'design.focus',
      status: 'approved',
      purpose: 'Support keyboard and pointer access.',
      implementation: 'design/ui/primitives.css',
      rules: [
        'Keep a visible focus ring on interactive controls. Noninteractive route focus targets use ae-focus-target with tabindex=-1 to receive focus without outlining the content region.',
        'Preserve browser shortcuts and editable input behavior.',
        'Workbench shortcuts use manifest-declared remappable Vim profiles with a disable option. No shortcut engine is implemented by AE Design.',
        'Native selects keep their semantics and use the shared select-indicator token for the dropdown mark. Native controls are the baseline. Custom focus traps, menus, and dialogs need a reviewed pattern.',
      ],
    },
    {
      id: 'design.states',
      status: 'approved',
      purpose: 'Make state and failures visible.',
      implementation: null,
      rules: [
        'Specify loading, empty, error, unavailable, disabled, and success behavior for each operation-backed control.',
        'Use text with status styling; never rely on color alone.',
        'Keep unknown values distinct from measured zero. Do not invent progress or live data.',
        'Prevent duplicate submissions while pending. Preserve user input after a failed request.',
        'Disabled controls must explain their limitation. UI state never substitutes for server authorization.',
      ],
    },
    {
      id: 'design.motion',
      status: 'approved',
      purpose: 'Keep motion optional.',
      implementation: 'design/ui/primitives.css',
      rules: [
        'Respect prefers-reduced-motion.',
        'No new autoplay motion, flicker, or attention loops except the owner-approved Open field motion: a single bird flight/lock sequence and user-triggered public navigation transitions, both with reduced-motion support.',
        'Static CRT texture belongs only to the approved research artwork.',
      ],
    },
  ],
  components: [
    {
      id: 'design.owner-access',
      status: 'approved',
      purpose: 'Open the single owner workspace with a passkey.',
      implementation: 'auth/ui/Access.tsx',
      rules: [
        'Owner approved ae-workbench/auth-launch on 2026-09-10. Use shared BrandMark, ThemeControl, tokens, native setup disclosure, and visible pending/error states.',
        'Keep /auth/me unlinked from public navigation. Setup takes a one-time secret; sign-in and later enrollment require passkeys.',
      ],
    },
    {
      id: 'design.navigation-selection',
      status: 'approved',
      purpose: 'Identify the current destination with a soft filled shape.',
      implementation: 'design/ui/primitives.css',
      rules: [
        'Apply ae-nav-item to a real navigation link. aria-current=page selects the rounded theme fill and stronger label.',
        'Keep every edge free of decorative stripes. Preserve a full visible keyboard focus ring.',
        'Use buttons for actions and do not mark unavailable pages as working links.',
      ],
    },
    {
      id: 'design.brand-mark',
      status: 'approved',
      purpose: 'Render the canonical brand asset.',
      implementation: 'design/ui/BrandMark.tsx',
      rules: [
        'Use color by default; provide a label only when the mark conveys information without adjacent text.',
      ],
    },
    {
      id: 'design.theme-control',
      status: 'approved',
      purpose: 'Render the theme selector.',
      implementation: 'design/ui/ThemeControl.tsx',
      rules: [
        'Use with the shared theme bootstrap; aria-pressed tracks the selected preference.',
      ],
    },
    {
      id: 'design.action-link',
      status: 'approved',
      purpose: 'Render a primary navigation action or a text link.',
      implementation: 'design/ui/ActionLink.tsx',
      rules: [
        'Use primary for the main destination, text for secondary destinations. Do not use a link for mutations.',
      ],
    },
    {
      id: 'design.download-group',
      status: 'approved',
      purpose: 'Present equivalent document downloads together.',
      implementation: 'design/ui/DownloadGroup.tsx',
      rules: [
        'Each link names its format and downloads a real file. Collapse vertically on narrow screens.',
      ],
    },
  ],
  patterns: [
    {
      id: 'design.publication-layout',
      status: 'approved',
      purpose:
        'Keep manuscript editing and publication settings visible together.',
      implementation: 'workspace/ui/writing/Publications.tsx',
      rules: [
        'Adopt the reviewed publication-layout prototype. Keep public preview on the shared public renderer and styles.',
        'Compact library navigation, a dominant manuscript canvas, formatting directly above it and a persistent right settings rail. On narrow screens, reveal settings through a native disclosure. Focus mode can hide surrounding navigation.',
        'Reuse AE tokens, brand, native controls, theme and focus behavior. Real Markdown and remappable Vim; do not imply WYSIWYG or working scheduled delivery.',
      ],
    },
    {
      id: 'design.public-navigation-transition',
      status: 'approved',
      purpose: 'Soften changes between public pages.',
      implementation: 'web/ui/shared/public-transitions.css',
      rules: [
        'Owner approved the slower prototype on 2026-09-09.',
        'Animate only content: 180ms exit, 400ms entrance after 60ms, with 4px upward settle.',
        'Show only one static root, header, and footer snapshot to avoid contrast changes.',
        'Use native document navigation. Reduced motion and unsupported browsers keep normal links and history. Workspace pages do not opt in.',
      ],
    },
    {
      id: 'design.work-field',
      status: 'approved',
      purpose:
        'Organize human and agent work by next action and dependency readiness.',
      implementation: null,
      rules: [
        'Owner authorized application implementation on 2026-09-09. Three-item focus, flat work rows, cross-space lenses, connected item details, and tracked system scope.',
        'Use shared tokens and native controls. No draggable columns, canvas gestures, custom dialogs, or new shortcut engine.',
        'Review both themes, narrow panes, keyboard return focus, empty states, unsaved input, and blocked actions before adoption.',
      ],
    },
    {
      id: 'design.writing-workflows',
      status: 'approved',
      purpose:
        'Separate fast personal capture from focused publication writing.',
      implementation: 'workspace/ui/writing/index.ts',
      rules: [
        'Owner approved the revised writing prototype for application implementation on 2026-09-09.',
        'Owner authorized the replacement publication prototype build on 2026-09-11. Keep Write, Split, Read, and saved-revision release review; Vim is the default editing profile and remains remappable. Org source stays protected from browser Markdown edits.',
        'Notes use a quick capture field and compact entries. Publications open from a library into one centered manuscript.',
        'Hide the workspace sidebar and header during publication writing. Keep save status and exit available; reveal settings, chapters, images, and publishing controls on request.',
        'Reuse AE Design typography, tokens, theme control, native dialogs, and visible keyboard focus. Vim editing is remappable and optional.',
      ],
    },
    {
      id: 'design.kanban',
      status: 'proposed',
      purpose: 'Track cards across named boards and review stages.',
      implementation: null,
      rules: [
        'Private prototype: ae-workbench/kanban/prototype.manifest.ts. Reuse workspace tokens, native forms, inline details, and shared theme controls.',
        'Use board selection, named columns, text blockers, and a keyboard-accessible move select. Stack columns on mobile. Review empty, invalid, conflict, unavailable, and saved states before adoption.',
        'Built requires evidence and owner review. Sample placements are not implementation findings.',
      ],
    },
    {
      id: 'design.observation-background-study',
      status: 'approved',
      purpose: 'Present the approved Open field home.',
      implementation: 'web/ui/landing/OpenField.tsx',
      rules: [
        'Owner approved Open field and optional animation on 2026-09-09. Center the introduction and contain the scene between header and footer.',
        'Light uses the approved bird paths and one corner-bracket detection box on the large middle bird, with no crosshairs. Dark uses the approved galaxy. Artwork opacity and alpha masks keep reading areas clear.',
        'Birds enter together once, using static silhouettes. Only the large middle bird receives a box, easing into a stop as detection locks. Dark mode uses the original static galaxy image. No motion button. Reduced motion and no JavaScript show static artwork. Pause when hidden. Never delay content or simulate live telemetry.',
      ],
    },
    {
      id: 'design.observation-window-study',
      status: 'proposed',
      purpose: 'Explore a dominant public observation window.',
      implementation: null,
      rules: [
        'Private prototype: ae-workbench/observation-window/prototype.manifest.ts. Compare a full-width window below editorial type with an immersive introduction inside the window.',
        'Reuse AE Design assets, theme behavior, and public copy. Preserve Readings as the primary action. Static artwork only; no simulated live measurements.',
        'Review both themes, narrow layouts, keyboard access, and text legibility before application adoption.',
      ],
    },
    {
      id: 'design.public-shell',
      status: 'approved',
      purpose: 'Frame the public pages.',
      implementation: 'web/adapters/http/public.tsx',
      rules: [
        'Use the existing brand, public navigation, theme selector, skip link, and footer. Feature content goes inside the shell.',
      ],
    },
    {
      id: 'design.about',
      status: 'approved',
      purpose: 'Present the owner profile.',
      implementation: 'web/ui/portfolio/AboutProfile.tsx',
      rules: [
        'Compact identity beside the approved bio; resume downloads and contact align below it. Stack at narrow widths.',
      ],
    },
    {
      id: 'design.research-field',
      status: 'approved',
      purpose:
        'Preserve the earlier research-window artwork for prototype references.',
      implementation: 'web/ui/landing/ObservationField.tsx',
      rules: [
        'Static recessed window; birds on light paper in dark mode, illustrated galaxy in light mode.',
        'This artwork is illustrative, not measured telemetry. Do not reuse its texture as workbench chrome.',
      ],
    },
    {
      id: 'design.reading',
      status: 'approved',
      purpose: 'Present readable articles.',
      implementation: 'web/adapters/http/public.tsx',
      rules: [
        'Use the existing serif reading column and semantic article structure. Scope display-title styling to the reader header; manuscript headings use a smaller hierarchy. Keep published content usable without JavaScript.',
        'Public inline backtick spans use italic serif emphasis; fenced code remains monospace. Reuse the theme accents and muted text for heading hierarchy.',
      ],
    },
    {
      id: 'design.guest-dashboard',
      status: 'approved',
      purpose:
        'Present the synthetic telemetry summary in the shared visual language.',
      implementation: 'dashboard/ui/guest/index.tsx',
      rules: [
        'Use the shared page background, theme logo, action states, and control radii. Preserve metric sources, units, and numerator/denominator evidence.',
      ],
    },
    {
      id: 'design.workbench-status',
      status: 'approved',
      purpose: 'Distinguish work states and soften workspace controls.',
      implementation: null,
      rules: [
        'Owner accepted sun/moon workspace colors, distinct review states, and rounded controls on 2026-09-09.',
        'Use status-progress for active work, status-ready for reviewable work, and status-attention for unresolved decisions. Always show a text label.',
        'Use workbench radius tokens for cards, controls, and dialogs. Existing public radii remain unchanged.',
        'Workspace accents are orange in light mode and blue in dark mode: sun and moon, as requested by the owner. The workbench active-surface gradient is limited to the featured in-progress card: warm orange in light mode, deep blue in dark mode. Navigation selection uses the workspace theme accent. The workbench shadow token provides restrained card elevation. Other panels stay flat.',
        'Use neutral semantic theme tokens for shared palette adoption. Review each new consumer in both themes and mobile; the accepted visual direction does not prove accessibility or runtime behavior.',
      ],
    },
    {
      id: 'design.workbench-shell',
      status: 'approved',
      purpose: 'Frame the accepted dashboard and Systems workspace.',
      implementation: null,
      rules: [
        'Owner accepted the workspace visual direction on 2026-09-09, with the sidebar stripe removed.',
        'Group Dashboard, Documents, Tasks, Experiments, Relationships, Publishing, Systems, Connections, and Access under Personal workspace; keep Public side separate.',
        'Current navigation uses a rounded soft fill, theme-colored icon and label, and medium text weight. No edge stripe, inset stripe shadow, or decorative side marker. Use design.navigation-selection.',
        'Use the public dark background gradient across the workspace. Keep panels solid and the sidebar distinct. Owner requested this on 2026-09-09.',
        'Open the dashboard on counts and work. Preserve the module-first Systems explorer with search, dependencies, contracts, bindings, and local console.',
        'Remove taglines, generic introductions, obvious interaction instructions, and redundant labels. Keep useful status, data source, and failure information.',
        'Use one page gutter and a 32px heading across workspace sections. Do not add a second page padding inside feature components. Keep forms compact and hide secondary creation or history panels behind native disclosures.',
        'Keep 14px controls and at least 12px metadata. Workspace cards use 14px corners and controls use 8px corners.',
        'The visual direction is approved; production routes, authorization, adapters, and behavior still require implementation and verification.',
      ],
    },
    {
      id: 'design.overlays',
      status: 'proposed',
      purpose: 'Standardize dialogs, menus, and command palettes.',
      implementation: null,
      rules: [
        'Review dismissal, focus restoration, keyboard behavior, and mobile layout before implementation.',
      ],
    },
  ],
  adoption: {
    consumers: ['web', 'dashboard', 'studio', 'system-explorer', 'workspace'],
    stylesheet: 'design/ui/index.css',
    componentEntrypoint: 'design/ui/index.ts',
    themeBootstrap: 'design/behaviors/theme.ts',
    exceptions: [
      {
        path: 'web/ui/landing/ObservationField.tsx',
        reason:
          'Illustration-specific SVG colors and geometry; not interface chrome.',
      },
    ],
    changeProcess: [
      'Read this manifest and the owning system manifest before UI work. Reuse approved components and patterns by their stable IDs.',
      'Public-page migration: adopt --ae-theme-accent, --ae-theme-accent-soft, --ae-theme-accent-contrast, and --ae-theme-ambient plus BrandMark variant theme. The older --ae-accent tokens retain existing public rendering until each consumer migrates.',
      'Keep approved public content, routes, artwork geometry, and reading behavior during visual migration. Workspace status-card gradients belong only to status cards; do not spread them across public page backgrounds.',
      'Read tokens.ts for foundation values, brand.ts for assets, and theme.ts for theme behavior. Never create parallel theme or logo implementations.',
      'If a required pattern is missing, declare it as proposed with its states and owning paths. Obtain prototype approval before adding new visual language.',
      'Use one writer for shared design files. Feature agents own their page composition and must coordinate changes to AE Design.',
      'Change a foundation at its source, run npm run design:sync, then mise run check and npm test. Review affected pages in both themes and narrow layouts.',
      'Keep exceptions explicit, narrow, and justified in this manifest. Do not add exceptions merely to silence a failing check.',
    ],
  },
  verification: {
    command: 'mise run check',
    tests: ['design/tests/design.test.ts', 'design/tests/theme.test.ts'],
    limits: [
      'Static checks catch token drift, prohibited hover-token use, known filler text, and declared contrast pairs. They do not prove rendered accessibility or visual quality.',
      'Focus order, browser theme behavior, and layout still need browser review.',
      'Private prototypes and engines are not scanned by public checks.',
    ],
  },
  contracts: [
    'design/contracts/design.schema.ts',
    'design/foundations/tokens.ts',
    'design/brand/brand.ts',
    'design/behaviors/theme.ts',
  ],
  operations: [],
  events: [],
  capabilityPaths: {
    foundations: 'design/foundations',
    brand: 'design/brand',
    behaviors: 'design/behaviors',
    components: 'design/ui',
    'design-validation': 'design/tests',
  },
  structure: { contracts: 'design/contracts', adapters: 'design/adapters' },
  entrypoints: [
    'design/ui/index.ts',
    'design/ui/index.css',
    'design/adapters/css/render.ts',
    'design/adapters/css/sync.ts',
    'design/tests/check.ts',
  ],
} as const satisfies DesignManifest;
