import {
  ownerProjectOperations,
  publicProjectOperations,
} from '../studio/authoring/manifest.ts';
import type { SystemManifest } from '../manifests/schema/system.schema.ts';

export default {
  kind: 'system',
  id: 'publishing',
  name: 'AE Publishing',
  purpose: 'Publish approved Studio revisions without Git deployments.',
  owner: 'amazingefren',
  status: 'declared',
  visibility: 'public',
  decisions: [
    'Studio owns private authoring. Publishing accepts an explicitly authorized, immutable revision through shared domain operations. Saving, previewing and external draft credentials never publish.',
    'Preserve existing IDs, slugs, approved snapshots, asset references and first publication instants. Record updates separately; display dates in the selected IANA timezone, default America/Denver.',
    'HTML, feeds, API responses and exports use the same approved revision and public assets. Never include private notes, evidence or source material.',
    'Publish full-text feeds with stable entry IDs and canonical links. Publishing does not require Git or deployment.',
    'Use revision preconditions for edits and transitions; use idempotency keys for create, publish, and withdraw.',
    'Activate the public revision only when its public assets are ready. Record refresh jobs durably and retry failed feeds, exports, and mirrors.',
    'Public lists read the active publication index at request time; invalidate revision caches on transitions. Private responses must not enter shared caches.',
    'Application delivery projects only active private-engine releases. Shared response caches stay disabled until withdrawal invalidation is verified. Scheduling, EPUB/PDF, mirrors and backup restoration are not enabled.',
    'Markdown, feeds and offline bundles retain approved source, including Mermaid fences. Browser diagrams are presentation only; offline bundles use local approved assets.',
    'Withdrawal removes the public listing, not downloaded, syndicated, or independently pinned copies.',
  ],
  capabilities: [
    'markdown-rendering',
    'publication-projects',
    'application-delivery',
    'publication',
    'exports',
    'rss',
    'atom',
    'markdown-downloads',
    'offline-bundles',
    'subscriptions',
    'changelog',
  ],
  governance: {
    permissionsDefined: [],
    dataClassification: 'mixed',
  },
  risks: [],
  dependencies: ['auth', 'studio'],
  schemaVersion: 6,
  contracts: [
    'contracts/writing/index.ts',
    'contracts/api/content-list.schema.json',
    'contracts/api/content.schema.json',
    'contracts/api/errors.schema.json',
    'contracts/api/list-input.schema.json',
    'contracts/api/read-input.schema.json',
    'contracts/content/publication-receipt.schema.json',
    'contracts/content/publication-transition.schema.json',
  ],
  operations: [
    ...ownerProjectOperations,
    ...publicProjectOperations,
    {
      id: 'publishing.list',
      access: {
        kind: 'public',
      },
      bindings: [
        {
          id: 'publishing.list.http',
          surface: {
            kind: 'http',
            method: 'GET',
            path: '/api/articles',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/http',
          testsDirectory: 'publishing/tests/adapters/http',
        },
        {
          id: 'publishing.list.mcp-tool',
          surface: {
            kind: 'mcp-tool',
            name: 'list_articles',
            description: 'List approved public articles.',
            readOnly: true,
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/mcp',
          testsDirectory: 'publishing/tests/adapters/mcp',
        },
        {
          id: 'publishing.list.cli',
          surface: {
            kind: 'cli',
            command: 'ae articles list',
            output: 'json',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/cli',
          testsDirectory: 'publishing/tests/adapters/cli',
        },
        {
          id: 'publishing.list.export',
          surface: {
            kind: 'export',
            format: 'markdown',
            path: '/exports/articles/index.md',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/exports/markdown',
          testsDirectory: 'publishing/tests/adapters/exports/markdown',
        },
        {
          id: 'publishing.list.offline',
          surface: {
            kind: 'export',
            format: 'offline-bundle',
            path: '/exports/articles.zip',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/exports/offline-bundle',
          testsDirectory: 'publishing/tests/adapters/exports/offline-bundle',
        },
        {
          id: 'publishing.list.onion',
          surface: {
            kind: 'mirror',
            network: 'onion',
            publicOnly: true,
            localAssets: true,
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/onion',
          testsDirectory: 'publishing/tests/adapters/onion',
        },
        {
          id: 'publishing.list.ipfs',
          surface: {
            kind: 'mirror',
            network: 'ipfs',
            publicOnly: true,
            localAssets: true,
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/ipfs',
          testsDirectory: 'publishing/tests/adapters/ipfs',
        },
        {
          id: 'publishing.list.rss',
          surface: {
            kind: 'feed',
            format: 'rss',
            path: '/feeds/articles.rss.xml',
            fullText: true,
            itemId: 'id',
            updatedAt: 'updatedAt',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/rss',
          testsDirectory: 'publishing/tests/adapters/rss',
        },
        {
          id: 'publishing.list.atom',
          surface: {
            kind: 'feed',
            format: 'atom',
            path: '/feeds/articles.atom.xml',
            fullText: true,
            itemId: 'id',
            updatedAt: 'updatedAt',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/atom',
          testsDirectory: 'publishing/tests/adapters/atom',
        },
      ],
      status: 'declared',
      input: 'contracts/api/list-input.schema.json',
      output: 'contracts/api/content-list.schema.json',
      errors: 'contracts/api/errors.schema.json',
      implementation: null,
      verification: [
        {
          id: 'publishing.list.contract',
          category: 'contract',
          expectation: 'Input and output conform to the referenced schemas.',
          tests: [],
        },
        {
          id: 'publishing.list.access',
          category: 'access',
          expectation:
            'Only approved public data is returned; private fields never appear.',
          tests: [],
        },
        {
          id: 'publishing.list.behavior',
          category: 'behavior',
          expectation:
            'All delivery bindings return the same approved revision.',
          tests: [],
        },
        {
          id: 'publishing.list.failure',
          category: 'failure',
          expectation:
            'Invalid input and missing data produce defined failures.',
          tests: [],
        },
      ],
      directory: 'publishing/operations/list',
      testsDirectory: 'publishing/tests/operations/list',
    },
    {
      id: 'publishing.read',
      access: {
        kind: 'public',
      },
      bindings: [
        {
          id: 'publishing.read.http',
          surface: {
            kind: 'http',
            method: 'GET',
            path: '/api/articles/{id}',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/http',
          testsDirectory: 'publishing/tests/adapters/http',
        },
        {
          id: 'publishing.read.mcp-tool',
          surface: {
            kind: 'mcp-tool',
            name: 'read_articles',
            description: 'Read approved public articles.',
            readOnly: true,
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/mcp',
          testsDirectory: 'publishing/tests/adapters/mcp',
        },
        {
          id: 'publishing.read.cli',
          surface: {
            kind: 'cli',
            command: 'ae articles read <id>',
            output: 'json',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/cli',
          testsDirectory: 'publishing/tests/adapters/cli',
        },
        {
          id: 'publishing.read.export',
          surface: {
            kind: 'export',
            format: 'markdown',
            path: '/exports/articles/{id}.md',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/exports/markdown',
          testsDirectory: 'publishing/tests/adapters/exports/markdown',
        },
        {
          id: 'publishing.read.mcp-resource',
          surface: {
            kind: 'mcp-resource',
            uriTemplate: 'ae://articles/{id}',
            mimeType: 'text/markdown',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/mcp',
          testsDirectory: 'publishing/tests/adapters/mcp',
        },
      ],
      status: 'declared',
      input: 'contracts/api/read-input.schema.json',
      output: 'contracts/api/content.schema.json',
      errors: 'contracts/api/errors.schema.json',
      implementation: null,
      verification: [
        {
          id: 'publishing.read.contract',
          category: 'contract',
          expectation: 'Input and output conform to the referenced schemas.',
          tests: [],
        },
        {
          id: 'publishing.read.access',
          category: 'access',
          expectation:
            'Only approved public data is returned; private fields never appear.',
          tests: [],
        },
        {
          id: 'publishing.read.behavior',
          category: 'behavior',
          expectation:
            'All delivery bindings return the same approved revision.',
          tests: [],
        },
        {
          id: 'publishing.read.failure',
          category: 'failure',
          expectation:
            'Invalid input and missing data produce defined failures.',
          tests: [],
        },
      ],
      directory: 'publishing/operations/read',
      testsDirectory: 'publishing/tests/operations/read',
    },
    {
      id: 'publishing.publish',
      access: {
        kind: 'authenticated',
        permissions: ['publishing.publish'],
        ownership: 'caller',
      },
      bindings: [
        {
          id: 'publishing.publish.http',
          surface: {
            kind: 'http',
            method: 'POST',
            path: '/api/publications/{id}/publish',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/http',
          testsDirectory: 'publishing/tests/adapters/http',
        },
        {
          id: 'publishing.publish.mcp-tool',
          surface: {
            kind: 'mcp-tool',
            name: 'publish',
            description: 'Publish for the authenticated owner.',
            readOnly: false,
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/mcp',
          testsDirectory: 'publishing/tests/adapters/mcp',
        },
        {
          id: 'publishing.publish.cli',
          surface: {
            kind: 'cli',
            command: 'ae publications publish <id>',
            output: 'json',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/cli',
          testsDirectory: 'publishing/tests/adapters/cli',
        },
      ],
      status: 'declared',
      input: 'contracts/content/publication-transition.schema.json',
      output: 'contracts/content/publication-receipt.schema.json',
      errors: 'contracts/api/errors.schema.json',
      directory: 'publishing/operations/publish',
      testsDirectory: 'publishing/tests/operations/publish',
      implementation: null,
      verification: [
        {
          id: 'publishing.publish.contract',
          category: 'contract',
          expectation:
            'Transition references the authorized source revision and returns a publication receipt without private material.',
          tests: [],
        },
        {
          id: 'publishing.publish.access',
          category: 'access',
          expectation:
            'Anonymous callers and non-owners cannot read or change private material.',
          tests: [],
        },
        {
          id: 'publishing.publish.behavior',
          category: 'behavior',
          expectation:
            'Draft edits remain private; only explicit publication changes the active public revision.',
          tests: [],
        },
        {
          id: 'publishing.publish.failure',
          category: 'failure',
          expectation:
            'Conflicting revisions and retry failures do not overwrite work or expose drafts.',
          tests: [],
        },
      ],
    },
    {
      id: 'publishing.withdraw',
      access: {
        kind: 'authenticated',
        permissions: ['publishing.publish'],
        ownership: 'caller',
      },
      bindings: [
        {
          id: 'publishing.withdraw.http',
          surface: {
            kind: 'http',
            method: 'POST',
            path: '/api/publications/{id}/withdraw',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/http',
          testsDirectory: 'publishing/tests/adapters/http',
        },
        {
          id: 'publishing.withdraw.mcp-tool',
          surface: {
            kind: 'mcp-tool',
            name: 'withdraw',
            description: 'Withdraw for the authenticated owner.',
            readOnly: false,
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/mcp',
          testsDirectory: 'publishing/tests/adapters/mcp',
        },
        {
          id: 'publishing.withdraw.cli',
          surface: {
            kind: 'cli',
            command: 'ae publications withdraw <id>',
            output: 'json',
          },
          status: 'declared',
          implementation: null,
          tests: [],
          directory: 'publishing/adapters/cli',
          testsDirectory: 'publishing/tests/adapters/cli',
        },
      ],
      status: 'declared',
      input: 'contracts/content/publication-transition.schema.json',
      output: 'contracts/content/publication-receipt.schema.json',
      errors: 'contracts/api/errors.schema.json',
      directory: 'publishing/operations/withdraw',
      testsDirectory: 'publishing/tests/operations/withdraw',
      implementation: null,
      verification: [
        {
          id: 'publishing.withdraw.contract',
          category: 'contract',
          expectation:
            'Transition references the authorized source revision and returns a publication receipt without private material.',
          tests: [],
        },
        {
          id: 'publishing.withdraw.access',
          category: 'access',
          expectation:
            'Anonymous callers and non-owners cannot read or change private material.',
          tests: [],
        },
        {
          id: 'publishing.withdraw.behavior',
          category: 'behavior',
          expectation:
            'Draft edits remain private; only explicit publication changes the active public revision.',
          tests: [],
        },
        {
          id: 'publishing.withdraw.failure',
          category: 'failure',
          expectation:
            'Conflicting revisions and retry failures do not overwrite work or expose drafts.',
          tests: [],
        },
      ],
    },
  ],
  capabilityPaths: {
    'markdown-rendering': 'publishing/rendering',
    'publication-projects': 'publishing/projects',
    'application-delivery': 'publishing/projects',
    publication: 'publishing/domain/publication',
    exports: 'publishing/adapters/exports',
    rss: 'publishing/adapters/rss',
    atom: 'publishing/adapters/atom',
    'markdown-downloads': 'publishing/adapters/exports/markdown',
    'offline-bundles': 'publishing/adapters/exports/offline-bundle',
    subscriptions: 'publishing/domain/subscriptions',
    changelog: 'publishing/domain/changelog',
  },
  structure: {
    domain: 'publishing/domain',
    operations: 'publishing/operations',
    ports: 'publishing/ports',
    adapters: 'publishing/adapters',
    tests: 'publishing/tests',
    composition: 'publishing/composition',
    distribution: 'publishing/operations/distribute',
    database: 'publishing/adapters/d1',
    assets: 'publishing/adapters/r2',
    migrations: 'publishing/migrations',
  },
  entrypoints: [
    'publishing/projects/delivery.ts',
    'publishing/domain/source/index.ts',
    'publishing/rendering/PublicationMarkdown.tsx',
  ],
} as const satisfies SystemManifest;
