import type { SystemManifest } from '../manifests/schema/system.schema.ts';

export default {
  kind: 'system',
  id: 'api',
  name: 'AE API',
  purpose: 'Compose HTTP interfaces over system operations.',
  owner: 'amazingefren',
  status: 'implemented',
  scope: 'required',
  visibility: 'public',
  context: {
    decisions: [
      'Thin HTTP gateway; domain logic stays in owning systems.',
      'Public OpenAPI 3.1 discovery derives implemented public HTTP bindings from the registry. Generic schemas retain public contract provenance; they do not infer payload validation from TypeScript source paths.',
      'Path normalization and duplicate template checks follow https://spec.openapis.org/oas/v3.1.0.html. Protected and synthetic operations are excluded.',
      'Expose public reading and catalog discovery without browser sessions.',
      'Use the same contracts and access decisions as MCP and CLI clients.',
    ],
    openQuestions: ['Versioning and error contracts.'],
  },
  capabilities: [
    'http-interface',
    'public-content-access',
    'public-system-access',
  ],
  governance: {
    permissionsDefined: [],
    dataClassification: 'mixed',
  },
  risks: [],
  dependencies: ['auth', 'publishing', 'system-explorer', 'studio'],
  schemaVersion: 5,
  contracts: ['api/contracts/openapi.ts'],
  operations: [
    {
      id: 'api.openapi',
      access: { kind: 'public' },
      dataScope: 'published',
      bindings: [
        {
          id: 'api.openapi.http',
          scope: 'required',
          status: 'implemented',
          directory: 'api/adapters',
          testsDirectory: 'api/tests',
          implementation: 'api/adapters/http.ts',
          tests: ['api/tests/openapi.test.ts'],
          surface: { kind: 'http', method: 'GET', path: '/api/openapi.json' },
        },
      ],
      status: 'implemented',
      input: 'api/contracts/openapi.ts',
      output: 'api/contracts/openapi.ts',
      errors: 'api/contracts/openapi.ts',
      directory: 'api/domain',
      testsDirectory: 'api/tests',
      implementation: 'api/domain/openapi.ts',
      verification: [
        {
          id: 'api.openapi.public-only',
          category: 'access',
          expectation: 'Only implemented public HTTP bindings appear.',
          tests: ['api/tests/openapi.test.ts'],
        },
        {
          id: 'api.openapi.contract',
          category: 'contract',
          expectation: 'The response is a deterministic OpenAPI 3.1 document.',
          tests: ['api/tests/openapi.test.ts'],
        },
        {
          id: 'api.openapi.failure',
          category: 'failure',
          expectation: 'Wrong methods and paths return typed HTTP failures.',
          tests: ['api/tests/openapi.test.ts'],
        },
      ],
    },
  ],
  events: [],
  capabilityPaths: {
    'http-interface': 'api/adapters',
    'public-content-access': 'api/gateway',
    'public-system-access': 'api/gateway',
  },
  structure: {
    domain: 'api/domain',
    operations: 'api/operations',
    ports: 'api/ports',
    adapters: 'api/adapters',
    tests: 'api/tests',
    composition: 'api/composition',
  },
  entrypoints: ['api/domain/openapi.ts', 'api/adapters/http.ts'],
} as const satisfies SystemManifest;
