import type { LaunchAccess } from './contracts/access.ts';
import type { SystemManifest } from '../manifests/schema/system.schema.ts';

export default {
  kind: 'system',
  id: 'web',
  name: 'AE Web',
  purpose: 'My portfolio and a place to read.',
  owner: 'amazingefren',
  status: 'declared',
  visibility: 'public',
  decisions: [
    'LOCAL_WORKSPACE_PREVIEW=true enables synthetic /workspace data only on HTTP loopback. Every other origin requires the owner session.',
    'The first release requires the owner passkey session for workspace and guest routes, APIs, and framework actions. Public guest hosting remains deferred; /auth/me stays unlinked.',
    'External draft routes accept scoped bearer credentials. Credential management requires an owner passkey session and same-origin mutations. Private responses never enter public caches.',
    'Public navigation uses full documents. Public pages remain readable without JavaScript; workspace pages do not use public view transitions.',
    'Readings and About me are the public destinations. The home uses approved Open field artwork and copy; AE Design owns its visual and motion constraints.',
    'Discovery files remain empty placeholders. No analytics or Cloudflare observability collection is enabled.',
    'Public builds require no private engines. Source authoring uses server-rendered TSX; MDX compilation is deferred until trusted published sources require it.',
    'Readings metadata comes from active snapshots: publication kind, tags, summary, word count, reading time and release dates. Never use draft mutation times as public update dates. Keep native links, chapter navigation and revision provenance available in server-rendered documents.',
    'The reading index leads with the latest publication, followed by compact archive rows.',
  ],
  capabilities: [
    'portfolio',
    'observation-landing',
    'reading',
    'no-javascript-reading',
  ],
  governance: {
    permissionsDefined: [],
    dataClassification: 'public',
  },
  risks: [],
  dependencies: [
    'design',
    'publishing',
    'resume',
    'system-explorer',
    'privacy',
    'studio',
    'dashboard',
    'api',
    'auth',
    'evaluation',
    'evidence',
    'mcp',
    'work',
    'workspace',
  ],
  schemaVersion: 6,
  launchAccess: {
    ownerPrefixes: [
      '/workspace',
      '/guest',
      '/api/workspace',
      '/api/guest',
      '/api/work',
      '/api/writing',
      '/api/dashboard',
      '/api/evaluation',
      '/api/evidence',
    ],
    signInPath: '/auth/me',
    frameworkActions: 'denied',
    tests: [
      'web/tests/access/access.test.ts',
      'web/tests/access/writing-gateway.test.ts',
      'web/tests/runtime/launch.mjs',
    ],
  },
  contracts: ['web/contracts/access.ts'],
  operations: [],
  pages: [
    {
      path: '/privacy',
      entrypoint: 'web/adapters/http/public.tsx',
      access: { kind: 'public' },
      status: 'implemented',
    },
    {
      path: '/',
      entrypoint: 'web/adapters/http/public.tsx',
      access: {
        kind: 'public',
      },
      status: 'implemented',
    },
    {
      path: '/readings',
      entrypoint: 'web/adapters/http/public.tsx',
      access: {
        kind: 'public',
      },
      status: 'implemented',
    },
    {
      path: '/readings/demo',
      entrypoint: 'web/adapters/http/public.tsx',
      access: {
        kind: 'public',
      },
      status: 'implemented',
    },
    {
      path: '/about',
      entrypoint: 'web/adapters/http/public.tsx',
      access: {
        kind: 'public',
      },
      status: 'implemented',
    },
    {
      path: '*',
      entrypoint: 'web/adapters/http/public.tsx',
      access: {
        kind: 'public',
      },
      status: 'implemented',
    },
  ],
  staticFiles: [
    {
      path: '/assets/galaxy-illustrated.png',
      source: 'web/public/assets/galaxy-illustrated.png',
      status: 'ready',
    },
    {
      path: '/assets/continuum-color.svg',
      source: 'web/public/assets/continuum-color.svg',
      status: 'ready',
    },
    {
      path: '/assets/continuum-blue.svg',
      source: 'web/public/assets/continuum-blue.svg',
      status: 'ready',
    },
    {
      path: '/assets/continuum-mono.svg',
      source: 'web/public/assets/continuum-mono.svg',
      status: 'ready',
    },
    {
      path: '/robots.txt',
      source: 'web/public/robots.txt',
      status: 'placeholder',
    },
    {
      path: '/llms.txt',
      source: 'web/public/llms.txt',
      status: 'placeholder',
    },
    {
      path: '/llms-full.txt',
      source: 'web/public/llms-full.txt',
      status: 'placeholder',
    },
    {
      path: '/agents.txt',
      source: 'web/public/agents.txt',
      status: 'placeholder',
    },
    {
      path: '/sitemap.xml',
      source: 'web/public/sitemap.xml',
      status: 'placeholder',
    },
    {
      path: '/.well-known/security.txt',
      source: 'web/public/.well-known/security.txt',
      status: 'placeholder',
    },
    {
      path: '/resume/Efren_Castro_Flagship_Resume.pdf',
      source: 'web/public/resume/Efren_Castro_Flagship_Resume.pdf',
      status: 'ready',
    },
    {
      path: '/resume/Efren_Castro_Flagship_Resume.docx',
      source: 'web/public/resume/Efren_Castro_Flagship_Resume.docx',
      status: 'ready',
    },
    {
      path: '/resume/Efren_Castro_Flagship_Resume.tex',
      source: 'web/public/resume/Efren_Castro_Flagship_Resume.tex',
      status: 'ready',
    },
  ],
  capabilityPaths: {
    portfolio: 'web/ui/portfolio',
    'observation-landing': 'web/ui/landing',
    reading: 'web/ui/readings',
    'no-javascript-reading': 'web/ui/readings',
  },
  structure: {
    publicShell: 'web/ui/shared',
    domain: 'web/domain',
    operations: 'web/operations',
    ports: 'web/ports',
    adapters: 'web/adapters',
    tests: 'web/tests',
    composition: 'web/composition',
    public: 'web/public',
  },
  entrypoints: [
    'web/vite.config.ts',
    'web/src/client.tsx',
    'web/composition/worker.tsx',
    'web/adapters/http/document.tsx',
    'web/package.json',
    'web/wrangler.jsonc',
  ],
} as const satisfies SystemManifest & { launchAccess: LaunchAccess };
